name=S29GL064S
version=1.0.0
author=Jack Pyburn
maintainer=Jack Pyburn <jwp0030@uah.edu>
sentence=A library to interface with the S29GL064S IC
paragraph=This library provides high-level functions for programming and erasing the S29GL064S family of NOR Flash ICs
url=
architectures=sam
